url: "https://sebdak.dev" # the base hostname & protocol for your site, e.g. http://example.com
title: Sebastian Knudsen
description: Software engineer, graphic designer and photographer
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default
keep_files: [CNAME, .git]
