url: "https://sebdak.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sebastian Knudsen" # the name of your site, e.g. ACME Corp.
# source: source
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default
